### ISSUE TITLE
Node icons in project tree can be a little funky

### ISSUE THREAD

**Issue by lachiesainsbury** [koosvary/Iconic#59]
**Branch**: develop

**Describe the bug**
Icons are not hidden when collapsing a project node in the project tree.

**To reproduce**
1. Create 2 new projects in the GUI.
2. Import a dataset for each project.
3. Collapse the project node arrows.
4. Observe the dataset icons not being hidden. Collapse the 2nd dataset and then the 1st dataset and observe that the folder icon and dataset icon are still shown.

**Expected behavior**
Dataset icons should be hidden from the project tree when projects are collapsed.

**Screenshots**
[Screenshot](https://i.imgur.com/JnXF8Ph.png)

**Additional context**
Icons are sexy regardless, gj jas

**Comment by ScottWalkerAU** [comment]
Looks fixed to me. Please verify @lachiesainsbury and close this
