### ISSUE TITLE
Settings.ini Functionality

### ISSUE THREAD

**Issue by Freakout2114** [koosvary/Iconic#7]
**Describe the solution you'd like**
The Command Line Interface(CLI) and GUI systems need the ability to load a default set of settings from a "defaultSettings.ini" file. These settings will determine:

- what building blocks will be available by default
- genetic algorithm to use by default
- error function
- objective function
- and anything else we can think about along the way.

The user will also have their own custom settings file. There are three options:
1. Using only one custom file ("userSettings.ini"). It will give the user the ability to pick their most common settings and allowing them to quickly start projects instead of tweeking every setting each time. 
2. (Prefered Option) The user has the ability to have as many as setting files as they want ("regressionSettings.ini", "windEnergyDataSettings.ini"). 
3. A combination of both (1) and (2). The user can define default settings for the loadup of every project, but each project the user has will have its own settings file, then when the user saves their project, all the settings will be saved and can be given to other users without the hastle of explaining what settings should be what. This file will be saved as "projectNameSettings.ini" and will be in the local directory of that project folder.

**Describe alternatives you've considered**
Alternatives are hard coding these options inplace but giving the user the ability to change things themselves is a better aproach in my opinion.

**Additional context**
N/A

**Comment by ScottWalkerAU** [comment]
The reading from the config file can be done very easily with existing libraries, no need to write your own.
May I suggest YAML?

**Comment by JasbirShah** [comment]
I'll do this for fun after the semester ends.
